### ISSUE TITLE
spec.podTemplateSpec.metadata.labels is not supported

### ISSUE THREAD

**Issue by aloksave** [stacklok/toolhive#2245]
## Bug description
My K8s cluster injects a proxy side car container in every pod as a security policy. his is done by adding a label on deployment. To make this needs me to add a spec.podTemplateSpec.metadata.labels on the MCPServer CRD. But i get the error: 

`Error from server (BadRequest): error when creating "k8s/mcp-server.yaml": MCPServer in version "v1alpha1" cannot be handled as a MCPServer: strict decoding error: unknown field "spec.podTemplateSpec.metadata.labels"`

## Steps to reproduce
```
Minimalistic MCPServer config example:
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: my-mcpserver
  namespace: default
spec:
  image: localhost:5000/my-mcpserver:latest
  transport: sse
  port: 8000
  targetPort: 8000
  env:
    - name: APP_ENDPOINT
      value: "https://sit-xxxxxx"
  podTemplateSpec:
    metadata:
      labels: 
        here_com_add_security_proxy_sidecar: null
```

## Expected behavior
I expected the Custom resource to be created as labels is said to be supported ont eh CDR spec

## Actual behavior
got the error: 
`Error from server (BadRequest): error when creating "k8s/mcp-server.yaml": MCPServer in version "v1alpha1" cannot be handled as a MCPServer: strict decoding error: unknown field "spec.podTemplateSpec.metadata.labels"`

## Environment (if relevant)
- OS/version:
Client Version: v1.33.4
Kustomize Version: v5.6.0
Server Version: v1.33.5-eks-113cf36
- ToolHive version:
toolhive-operator-crds: 0.0.34
toolhive-operator: 0.2.21

**Comment by ChrisJBurns** [comment]
Thanks for raising this @aloksave. I think this may have been fixed in later version of ToolHive and it's CRDs. Can you verify if you get this problem on `v0.0.41` of the CRDs Chart and `0.3.0` of the Operator chart? 

I've ran a basic test on my end with them and can confirm that the labels don't cause issues when applying, but you may have to quote the `true` string.

```yaml
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: my-mcpserver
  namespace: toolhive-system
spec:
  image: ghcr.io/stackloklabs/gofetch/server
  transport: sse
  port: 8000
  targetPort: 8000
  env:
    - name: APP_ENDPOINT
      value: "https://sit-xxxxxx"
  podTemplateSpec:
    metadata:
      labels: 
        security_proxy_sidecar: "true"
```

**Comment by aloksave** [comment]
@ChrisJBurns Thanks for the response. 
I checked on the versions you suggested: 
toolhive-operator-crds:0.0.41
toolhive-operator:0.3.0
But i still get the same behavior. "spec.podTemplateSpec.metadata.labels" is not recognized. 

I also checked on the latest versions(as of today 25-Oct) with the same outcome:
toolhive-operator-crds:0.0.44
toolhive-operator:0.3.1

Additional note: It seems some new CRDs were introduced over the last week which need to be manually applied over the operator helm upgrade for operator pod to get to running state. Didn't find a mention of this anywhere. I know there is a lot of development happening on the operator and CDR right now and both are in alpha state but it will help if new upgrades or installation instructions especially regarding breaking changes can be called out.

**Comment by ChrisJBurns** [comment]
@aloksave  Yeah I think it was likely that your CRDs weren't upgrade because of the way we've built the CRDs Chart. We are going to be bringing in a new Helm CRD solution soon that will allow people to upgrade their CRDs. We have the CRDs Chart but the CRDs themselves are in the `crds/` directory which Helm uses to install them but not upgrade them. For reference, we will be going with Option 3 of  https://github.com/stacklok/toolhive/issues/2518. This allows us to package things together and to remove the hassle and complexity of users having to maintain alignment between two separate charts

**Comment by ChrisJBurns** [comment]
@aloksave  This should be achievable now with our new helm charts for the [`operator-crds`](https://github.com/stacklok/toolhive/releases/tag/toolhive-operator-crds-0.0.80). By default the CRDs themselves should get updated when you install via Helm.
