### ISSUE TITLE
Restart proxy processes after a reboot

### ISSUE THREAD

**Issue by danbarr** [stacklok/toolhive#431]
In #135 we added a restart policy to the MCP containers so they come back up after a reboot, but the proxy processes do not restart, so the containers aren't reachable by clients until you `restart` each one to re-launch the proxy.

It would be nice to handle reboots gracefully and bring back not only the container but also the proxy.

**Comment by yrobla** [comment]
@danbarr  is this still applying or that was fixed?

**Comment by danbarr** [comment]
It's still an issue, but probably difficult to solve in the CLI currently since there's no service process that stops/starts on logout/login that could record & restore the state of MCP servers. The containers restart after you log back in, but the proxies don't. `thv restart --all` helps but isn't automatic.

**Comment by dmjb** [comment]
I think this is something we want to build on top of the status tracking. I think we want to have a dedicated state for workloads which were running during a shutdown of ToolHive, and which we want to restart on a reboot.

The other issue is figuring out how this will work for the CLI. For the API/UI, there is a logical place for this to happen - when the API process starts. For the CLI, this is less straightforward... since there is no background process. There has been some discussion around changing the CLI to reuse the API, but that has not been decided upon for sure.

**Comment by danbarr** [comment]
Since the introduction of remote MCPs, there is some updated behavior to note.

After a reboot today, `thv list` showed my remote MCP servers as `running`, which was incorrect since their proxy processes were gone. I had to stop/start them to get working again.

Also it seems the `unless-stopped` restart policy was reverted at some point, the containers for local MCPs no longer come back up after a reboot either, and those workloads show `unknown` state until restarted with `thv restart`.

There's a [corollary with the UI too](https://github.com/stacklok/toolhive-studio/issues/938). Normally on an app shutdown, the UI records the state of currently running MCPs, gracefully shuts them down, then re-starts them when the app is re-opened. But this doesn't have a chance to happen during an OS restart since the ToolHive UI shutdown doesn't block the OS restart too accomplish this, like other apps do with "do you want to save..." and similar dialogs.
